version: "3"

volumes:
  data:

services:
  express:
    image: puneetsarhali/note-taker_express:1
    depends_on:
      - postgres
    ports:
      - 3001:3001
  frontend:
    image: puneetsarhali/note-taker_frontend:1
    depends_on:
      - express
    ports:
      - 3000:4200
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432
    volumes:
      - data:/var/lib/postgresql
